### ISSUE TITLE
Providing setup instruction.

### ISSUE THREAD

**Issue by Dharansh-Neema** [Artlfmj/course-manager#40] opened 2023-10-02 20:42 UTC
Editing the readme.md file to provide comprehensive setup instructions for new contributors. The inclusion of clear setup instructions is essential for ensuring a seamless and efficient development process within the repository.

**Comment by Sushannt** [comment] 2023-10-03 04:57
please assign this to me.

**Comment by Artlfmj** [comment] 2023-10-03 04:58
@Sushannt gi ahead, but please make it into a Setup.md file

**Comment by Artlfmj** [comment] 2023-10-03 04:58
Wait this is a duplicate of #30

**Closed by Artlfmj** 2023-10-03 04:58 UTC

**Comment by Artlfmj** [comment] 2023-10-03 05:02
@Sushannt please ask to be assigned to another issue :)
